Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "db01"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell",
  path: "provision.sh"

end


# Vagrant.configure("2") do |config|
#     config.vm.box = "debian/bookworm64"
#     config.vm.hostname = "db01"
#     config.vm.network "private_network", ip: "192.168.1.4"
#     config.vm.network "forwarded_port", guest: 3306, host: 3306
#     config.vm.provision "shell", path: "provision.sh"
#   end